# Use the specified Node.js version
FROM node:21.4.0

# Set the working directory in the container
WORKDIR /index.js

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --quiet

# Copy the entire project to the working directory
COPY . .

# Expose the port the app runs on if necessary (e.g., Metro bundler port)
EXPOSE 8081

# Start the React Native packager
CMD ["npm", "start"]
